"""Metadata for calendar2mastodon. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__title__",
    "__version__",
    "__description__",
    "__readme__",
    "__credits__",
    "__keywords__",
    "__license__",
    "__requires_python__",
    "__status__",
]

__title__ = "calendar2mastodon"
__version__ = "0.1.0"
__description__ = "A Python tool to post calendar events to Mastodon"
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["calendar2mastodon"]
__license__ = "MIT"
__requires_python__ = ">=3.9"
__status__ = "3 - Alpha"
